[unix_http_server]
file=/run/supervisord.sock

[supervisord]
nodaemon=true
logfile=/var/www/html/storage/logs/supervisord.log
pidfile=/tmp/supervisord.pid

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///run/supervisord.sock

[program:queue-default]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/artisan queue:work redis --sleep=1 --tries=3 --max-time=3600 --timeout=300 --backoff=10,30,60 --rest=0.1
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=4
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/worker-default.log
stopwaitsecs=30

[program:queue-imports]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/artisan queue:work redis --queue=imports --sleep=1 --tries=3 --max-time=3600 --timeout=600 --backoff=10,30,60 --rest=0.1
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=8
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/worker-imports.log
stopwaitsecs=60

[program:queue-exports]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/artisan queue:work redis --queue=exports --sleep=1 --tries=3 --max-time=3600 --timeout=600 --backoff=10,30,60 --rest=0.1
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=4
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/worker-exports.log
stopwaitsecs=60
